import:
  - ~/.alacritty-colorscheme/themes/gruvbox_dark.yaml

window:
  decorations: full
  dynamic_padding: true

font:
  normal:
    family: Inconsolata
    style: Regular

  bold:
    family: Inconsolata
    style: Bold

  italic:
    family: Inconsolata
    style: Italic

  bold_italic:
    family: Inconsolata
    style: Bold Italic

  # External monitor
  size: 13
  # Laptop monitor
  #size: 9
